name: build-echoo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.6'
    - run: go version
    - name: Build echoo
      run: |
        bash build.sh
        ls -la dist || true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: latest-build
        path: |
          dist